# Generated by Django 6.0.6 on 2026-08-16 08:23

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.expressions.Case, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accountuser',
            index=models.Index(fields=['email'], name='global_user_email_04c0d8_idx'),
        ),
        migrations.AddIndex(
            model_name='accountuser',
            index=models.Index(fields=['tenant'], name='global_user_tenant__14c035_idx'),
        ),
        migrations.AddIndex(
            model_name='accountuser',
            index=models.Index(fields=['phone_number'], name='global_user_phone_n_00a79e_idx'),
        ),
    ]
