# Generated by Django 6.0.6 on 2026-08-16 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('standard', 'Standard'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=dict, null=True)),
                ('limit', models.JSONField(blank=True, default=dict, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Panding'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('sent', 'Sent'), ('draft', 'Draft'), ('cancelled', 'Cancelled')], max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('payment_status', models.CharField(blank=True, choices=[('pending', 'Panding'), ('paid', 'Paid'), ('failed', 'Failed'), ('refund', 'Refund'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('crdb', 'CRDB'), ('nmb', 'NMB'), ('m-pesa', 'M-pesa'), ('halo-pesa', 'Halo-pesa'), ('mix-by-yas', 'Mix-By-Yas'), ('airtel-money', 'Airtel-Money')], max_length=50, null=True)),
                ('payment_referance', models.CharField(blank=True, max_length=100, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=200, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('crdb', 'CRDB'), ('nmb', 'NMB'), ('m-pesa', 'M-pesa'), ('halo-pesa', 'Halo-pesa'), ('mix-by-yas', 'Mix-By-Yas'), ('airtel-money', 'Airtel-Money')], max_length=50, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Panding'), ('paid', 'Paid'), ('failed', 'Failed'), ('refund', 'Refund'), ('cancelled', 'Cancelled')], max_length=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reminder_type', models.CharField(blank=True, choices=[('sms', 'SMS'), ('email', 'Email'), ('both', 'Both')], max_length=50, null=True)),
                ('scheduled_date', models.DateTimeField()),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField()),
                ('error_message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Panding'), ('sent', 'Sent'), ('failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='subscriptions.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_months', models.PositiveBigIntegerField(choices=[(14, '14 days'), (1, '1 Month'), (2, '2 Months'), (3, '3 Months'), (6, '6 Months'), (12, '12 Months')])),
                ('badge', models.CharField(blank=True, choices=[('popular', 'Popular'), ('best_value', 'Best Value')], max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='subscriptions.subscriptionplan')),
            ],
            options={
                'unique_together': {('plan', 'duration_months')},
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('pending', 'Panding'), ('paid', 'Paid'), ('failed', 'Failed'), ('refund', 'Refund'), ('cancelled', 'Cancelled')], max_length=20)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.planpricing')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='subcription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.tenantsubscription'),
        ),
    ]
