# Generated by Django 6.0.6 on 2026-08-16 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('staff_id', models.CharField(editable=False, help_text='Auto-generated: e.g., TAD-2025-0001', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('failed_login', models.PositiveIntegerField(default=0)),
                ('registed_date', models.DateTimeField(auto_now_add=True)),
                ('global_user', models.OneToOneField(blank=True, help_text='Linked GlobalUser for Authentication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.role')),
            ],
            options={
                'db_table': 'tenant_users',
                'indexes': [models.Index(fields=['global_user'], name='tenant_user_global__803e21_idx'), models.Index(fields=['staff_id'], name='tenant_user_staff_i_54f0b4_idx')],
            },
        ),
    ]
