# Generated by Django 6.0.6 on 2026-08-16 08:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('branch_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164 format.', regex='^\\+[1-9]\\d{1,14}$')])),
                ('bank_details', models.TextField(blank=True, null=True)),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_code', models.CharField(max_length=20)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_footer', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('branch_address', models.CharField(blank=True, max_length=100, null=True)),
                ('is_head_office', models.BooleanField(default=False)),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('email_onInvoice', models.BooleanField(default=False)),
                ('phone_onInvoice', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='companies.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='currency.currency')),
            ],
            options={
                'indexes': [models.Index(fields=['company'], name='branches_br_company_c6a45b_idx'), models.Index(fields=['slug'], name='branches_br_slug_91f057_idx')],
                'unique_together': {('company', 'branch_code'), ('company', 'branch_name')},
            },
        ),
    ]
