# Generated by Django 6.0.6 on 2026-08-16 08:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('key', models.CharField(blank=True, max_length=20, null=True)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='company/language/')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('schema_name', models.CharField(blank=True, max_length=63, unique=True)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(choices=[('left', 'LTR'), ('right', 'RTL')], default='left', max_length=50)),
                ('menu_position', models.CharField(choices=[('top_bottom', 'Top & Bottom'), ('top_header', 'Top Header'), ('bottom_corner', 'Bottom Corner')], default='top_bottom', max_length=50)),
                ('timezone', models.CharField(default='Africa/Dar_es_Salaam', max_length=50)),
                ('detect_timezone', models.BooleanField(default=True)),
                ('date_format', models.CharField(blank=True, choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=50, null=True)),
                ('time_format', models.CharField(blank=True, choices=[('12h', '12 Hour (AM/PM)'), ('24h', '24 Hour')], default='24h', max_length=50, null=True)),
                ('receipt_footer', models.TextField(blank=True)),
                ('enable_tax', models.BooleanField(default=True)),
                ('low_stock_alert', models.BooleanField(default=True)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='companies.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='currency.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
